name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy_static_html:
    runs-on: ubuntu-latest
    name: Deploy Static HTML
    steps:
      - uses: actions/checkout@v2

      - name: Upload HTML files to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"            # root folder of your index.html
          output_location: ""          # empty since there’s no build step
